"""Continue cross-region control transfers inside generated code.

DolRecomp emits one function per 256-instruction region. Every call, return or
branch that leaves a region stores the guest PC and returns to the C++ run loop,
which re-dispatches through the module table: the browser build measured about
267,000 such dispatches per frame. This pass rewrites those exits so that, when
the run loop's own conditions still hold, the region tail-calls the next one
directly through an ordinary call (V8 runs wasm tail calls far slower than
calls; the chain's cycle budget bounds the call depth). The run loop keeps
every other boundary: exceptions, interpreter
fallbacks, rfi, loop-budget exhaustion, hook addresses, unverified regions and
guest contexts other than the run loop's. Instruction bodies, PC stores and
cycle charges are unchanged.

A transfer continues only when all of these hold (see opensmash_chain.h):
- the CPUState is the run loop's registered context,
- no exception is pending,
- the accumulated cycle charge is within the dispatch's chain budget: the cycles
  left in the CoreTiming slice, capped at DOLRECOMP_C_LOOP_CYCLE_BUDGET. A chain
  therefore ends at the first transfer after the slice expires, which is where
  per-region dispatch ended its burst, so interrupt delivery points are the same;
  as in the run loop, a transfer that charged nothing since the previous one
  charges one cycle,
- the target is not a host-call (patch or hook) address or a configured idle
  loop address, which the run loop must observe,
- the target region is verified against guest RAM by the chassis SMC guard and
  is not one the chassis forces through the interpreter.
"""
import bisect
import json
import re
from pathlib import Path

from specialize_browser_math import GENERATED

STATIC_SITE = re.compile(r'([ \t]*)ctx->pc = 0x([0-9A-F]{8})u;\n\1return;\n')
DYNAMIC_SITE = re.compile(r'([ \t]*)ctx->pc = target;\n\1return;\n')
RETURN_DISPATCH = re.compile(
    r'(return_dispatch_[0-9A-F]{8}:\n'
    r'    if \(ctx->downcount <= -\(s64\)DOLRECOMP_C_LOOP_CYCLE_BUDGET\) return;\n'
    r'    switch \(ctx->pc\) \{\n'
    r'(?:    case 0x[0-9A-F]{8}u: goto label_[0-9A-F]{8};\n)*)'
    r'    default: return;\n')


def chunk_table(generated):
    """Region index, base and end exactly as module-template/gen_module_tables.py."""
    header = (generated / 'generated.h').read_text()
    ranges = {(int(a, 16), int(b, 16)) for a, b in re.findall(
        r'address >= (0x[0-9A-Fa-f]+)u && address < (0x[0-9A-Fa-f]+)u', header)}
    for base, span in re.findall(
            r'u32\s+offset\s*=\s*address\s*-\s*(0x[0-9A-Fa-f]+)u\s*;\s*'
            r'if\s*\(\s*offset\s*<\s*(0x[0-9A-Fa-f]+)u', header):
        ranges.add((int(base, 16), int(base, 16) + int(span, 16)))
    ranges = sorted(ranges)
    bases = sorted(int(a, 16) for a in re.findall(
        r'void func_([0-9A-Fa-f]{8})\(CPUState\* ctx\);', header))
    chunks = []
    for i, base in enumerate(bases):
        containing = next((r for r in ranges if r[0] <= base < r[1]), None)
        if containing is None:
            raise ValueError(f'func_{base:08X} outside all code ranges')
        end = containing[1]
        if i + 1 < len(bases) and containing[0] <= bases[i + 1] < containing[1]:
            end = bases[i + 1]
        chunks.append((base, end))
    return chunks


def write_changed(path, text):
    if not path.exists() or path.read_text() != text:
        path.write_text(text)


def chain_header(chunks):
    lines = ['#pragma once',
             '// Generated by tools/chain_browser_chunks.py. See that file for the',
             '// conditions under which a region continues into the next one.',
             '#include "generated.h"',
             '',
             '// Only the run loop\'s guest context chains; other users of the module',
             '// dispatcher (oracles, tests) keep single-region dispatch semantics.',
             'extern CPUState* opensmash_chain_ctx;',
             '// Dense stop bitmap for 0x80000000..0x80400000 (host-call and idle-loop',
             '// addresses the run loop must observe), or NULL for no chaining.',
             'extern u64* opensmash_chain_hook_bits;',
             '// Cycle budget for the current dispatch: the cycles left in the run loop\'s',
             '// CoreTiming slice, so a chain ends where per-region dispatch ended its burst.',
             'extern s64 opensmash_chain_budget;',
             '// Chassis region states (0 unverified, 1 verified, 2 failed), indexed as below,',
             '// and regions the chassis forces through the interpreter (host-call regions).',
             'extern const u8* opensmash_chain_chunk_state;',
             'extern const u8* opensmash_chain_chunk_forced;',
             '// Differential testing: the target a non-chained exit would have continued to.',
             'extern u32 opensmash_chain_last;',
             '// Accumulated charge at the previous transfer: like the run loop, every',
             '// region transfer charges at least one cycle, so zero-charge loops end.',
             'extern s64 opensmash_chain_mark;',
             '// Run-loop burst snapshot; pending dispatch cycles advance TB at each transfer.',
             'extern u64 opensmash_chain_tb_base, opensmash_chain_tb_cycles;',
             f'#define OPENSMASH_CHAIN_CHUNKS {len(chunks)}u',
             'extern const u32 opensmash_chain_chunk_count;',
             'extern const u32 opensmash_chain_chunk_base[OPENSMASH_CHAIN_CHUNKS];',
             '',
             'static inline int opensmash_chain_index(u32 address) {']
    # Contiguous runs of equally sized regions share one arithmetic lookup.
    runs = []
    for index, (base, end) in enumerate(chunks):
        if runs and runs[-1][1] == base and runs[-1][3] == end - base:
            runs[-1][1] = end
        else:
            runs.append([base, end, index, end - base])
    for base, end, index, size in runs:
        for i in range((end - base) // size):
            if chunks[index + i] != (base + i * size, base + (i + 1) * size):
                raise ValueError('irregular region layout')
        lines.append(f'    if (address >= 0x{base:08X}u && address < 0x{end:08X}u)')
        lines.append(f'        return {index} + (int)((address - 0x{base:08X}u) / 0x{size:X}u);')
    lines += ['    return -1;',
              '}',
              'static inline bool opensmash_chain_hooked(u32 address) {',
              '    u32 offset = address - 0x80000000u;',
              '    if (offset >= 0x00400000u || (offset & 3u)) return true;',
              '    return (opensmash_chain_hook_bits[offset >> 8] >> ((offset >> 2) & 63u)) & 1u;',
              '}',
              '// The decision the run loop would make for this target, without the context check.',
              'static inline bool opensmash_chain_would(const CPUState* ctx, u32 target, int index) {',
              '    return !ctx->exception && opensmash_chain_hook_bits &&',
              '        ctx->downcount > -opensmash_chain_budget &&',
              '        index >= 0 && opensmash_chain_chunk_state[index] == 1u &&',
              '        !opensmash_chain_chunk_forced[index] &&',
              '        !opensmash_chain_hooked(target);',
              '}',
              'static inline bool opensmash_chain_ok(const CPUState* ctx, u32 target, int index) {',
              '    return ctx == opensmash_chain_ctx && opensmash_chain_would(ctx, target, index);',
              '}',
              '// Out of line: the check is one call per exit site, keeping regions small.',
              'bool opensmash_chain_test(CPUState* ctx, u32 target, int index);',
              'DolRecompFunction opensmash_chain_resolve(CPUState* ctx, u32 target);',
              '#define OPENSMASH_CHAIN_STATIC(fn, target, index) do { \\',
              '    if (opensmash_chain_test(ctx, target, index)) fn(ctx); \\',
              '    return; } while (0)',
              '#define OPENSMASH_CHAIN_DYNAMIC(target) do { \\',
              '    DolRecompFunction chain_fn_ = opensmash_chain_resolve(ctx, (target)); \\',
              '    if (chain_fn_) chain_fn_(ctx); \\',
              '    return; } while (0)',
              '']
    return '\n'.join(lines)


def chain_source(chunks):
    text = ['// Generated by tools/chain_browser_chunks.py.',
            '#include "opensmash_chain.h"',
            'CPUState* opensmash_chain_ctx = NULL;',
            'u64* opensmash_chain_hook_bits = NULL;',
            's64 opensmash_chain_budget = DOLRECOMP_C_LOOP_CYCLE_BUDGET;',
            'const u8* opensmash_chain_chunk_state = NULL;',
            'const u8* opensmash_chain_chunk_forced = NULL;',
            'u32 opensmash_chain_last = 0;',
            's64 opensmash_chain_mark = 0;',
            'u64 opensmash_chain_tb_base = 0, opensmash_chain_tb_cycles = 0;',
            'const u32 opensmash_chain_chunk_count = OPENSMASH_CHAIN_CHUNKS;',
            'static inline void opensmash_chain_charge(CPUState* ctx) {',
            '    if (ctx->downcount == opensmash_chain_mark) ctx->downcount -= 1;',
            '    opensmash_chain_mark = ctx->downcount;',
            '}',
            'bool opensmash_chain_test(CPUState* ctx, u32 target, int index) {',
            '    if (ctx == opensmash_chain_ctx) {',
            '        opensmash_chain_charge(ctx);',
            '        if (opensmash_chain_would(ctx, target, index)) {',
            '            ctx->timebase = opensmash_chain_tb_base +',
            '                (opensmash_chain_tb_cycles - (u64)ctx->downcount) / 12u;',
            '            return true;',
            '        }',
            '    }',
            '    opensmash_chain_last = target;',
            '    return false;',
            '}',
            'DolRecompFunction opensmash_chain_resolve(CPUState* ctx, u32 target) {',
            '    if (ctx == opensmash_chain_ctx) {',
            '        opensmash_chain_charge(ctx);',
            '        if (opensmash_chain_would(ctx, target, opensmash_chain_index(target))) {',
            '            DolRecompFunction fn = dolrecomp_find_original(target);',
            '            if (fn) {',
            '                ctx->timebase = opensmash_chain_tb_base +',
            '                    (opensmash_chain_tb_cycles - (u64)ctx->downcount) / 12u;',
            '                return fn;',
            '            }',
            '        }',
            '    }',
            '    opensmash_chain_last = target;',
            '    return NULL;',
            '}',
            'const u32 opensmash_chain_chunk_base[OPENSMASH_CHAIN_CHUNKS] = {']
    text += [f'    0x{base:08X}u,' for base, _ in chunks]
    text += ['};', '']
    return '\n'.join(text)


def rewrite(source, chunks, stats):
    bases = [base for base, _ in chunks]

    def chunk_of(address):
        i = bisect.bisect_right(bases, address) - 1
        if i >= 0 and chunks[i][0] <= address < chunks[i][1]:
            return i
        return -1

    def static_site(match):
        indent, address = match[1], int(match[2], 16)
        before = source[:match.start()].rstrip('\n').rsplit('\n', 1)[-1]
        if 'DOLRECOMP_C_LOOP_CYCLE_BUDGET' in before:
            stats['budgetExits'] += 1
            return match[0]
        index = chunk_of(address)
        if index < 0:
            stats['unmappedExits'] += 1
            return match[0]
        stats['staticExits'] += 1
        return (f'{indent}ctx->pc = 0x{address:08X}u;\n'
                f'{indent}OPENSMASH_CHAIN_STATIC(func_{chunks[index][0]:08X}, 0x{address:08X}u, {index});\n')

    def dynamic_site(match):
        stats['dynamicExits'] += 1
        return f'{match[1]}ctx->pc = target;\n{match[1]}OPENSMASH_CHAIN_DYNAMIC(target);\n'

    def return_dispatch(match):
        stats['returnDispatchExits'] += 1
        return match[1] + '    default: OPENSMASH_CHAIN_DYNAMIC(ctx->pc);\n'

    text = STATIC_SITE.sub(static_site, source)
    text = DYNAMIC_SITE.sub(dynamic_site, text)
    text = RETURN_DISPATCH.sub(return_dispatch, text)
    text = text.replace('#include "../', '#include "../../')
    generated_include = '#include "../../generated.h"\n'
    if generated_include not in text:
        raise ValueError('Missing generated.h include')
    return text.replace(generated_include,
                        generated_include + '#include "../../opensmash_chain.h"\n', 1)


def chain_chunks(generated=GENERATED):
    chunks = chunk_table(generated)
    output = generated / 'chained'
    for kind in ('chunks', 'entries', 'deferred'):
        (output / kind).mkdir(parents=True, exist_ok=True)
    write_changed(generated / 'opensmash_chain.h', chain_header(chunks))
    write_changed(generated / 'opensmash_chain.c', chain_source(chunks))
    stats = {'regions': len(chunks), 'files': 0, 'staticExits': 0, 'dynamicExits': 0,
             'returnDispatchExits': 0, 'budgetExits': 0, 'unmappedExits': 0}
    manifest = ['set(OPENSMASH_CHUNKS\n', f'  "{(generated / "opensmash_chain.c").as_posix()}"\n']
    entries = {path.name for path in (generated / 'entries').glob('*.c')}
    deferred = {path.name for path in (generated / 'deferred').glob('*.c')}
    stale = {path.name for kind in ('chunks', 'entries', 'deferred') for path in (output / kind).glob('*.c')}
    for original in sorted((generated / 'chunks').glob('*.c')):
        kind = ('entries' if original.name in entries else
                'deferred' if original.name in deferred else 'chunks')
        source = (generated / kind / original.name).read_text()
        destination = output / kind / original.name
        write_changed(destination, rewrite(source, chunks, stats))
        stale.discard(original.name)
        manifest.append(f'  "{destination.as_posix()}"\n')
        stats['files'] += 1
    for name in stale:
        for kind in ('chunks', 'entries', 'deferred'):
            (output / kind / name).unlink(missing_ok=True)
    manifest.append(')\n')
    write_changed(generated / 'opensmash_chained.cmake', ''.join(manifest))
    write_changed(generated / 'opensmash_chain.json', json.dumps(stats, indent=2) + '\n')
    return stats


if __name__ == '__main__':
    print(json.dumps(chain_chunks(), indent=2))
