"""Specialize a verified, straight-line SDK routine without changing its math.

The generic path remains available for exceptions, quantized GQRs and non-RAM
addresses. Full CPU and RAM differential validation lives in validate_browser_math.py.
"""
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / 'build/browser-engine/melee-wasm-code/generated'
CHUNK = GENERATED / 'chunks/chunk_3324_text1_80342140.c'


def containing_chunk(generated, address):
    chunks = sorted(generated.glob('chunks/*.c'), key=lambda p: int(p.stem.rsplit('_', 1)[1], 16))
    return next(path for path in reversed(chunks) if int(path.stem.rsplit('_', 1)[1], 16) <= address)


def specialize(generated=GENERATED):
    chunk = containing_chunk(generated, 0x80342204)
    boundary = chunk.stem.rsplit('_', 1)[1]
    source = chunk.read_text()
    # Idempotent: the generated generic routine remains the reference oracle.
    source = source.replace('#include "../opensmash_concat.h"\n', '')
    source = source.replace('    if (opensmash_concat(ctx)) return;\n', '')
    body = source.split('label_80342204:\n', 1)[1].split('label_803422D0:', 1)[0].replace('return_dispatch_'+boundary, 'return_dispatch_80342140')
    expected = 'e186fe78bdb7942081d21a898a99bbaff1ea05055c93877a1baf503ac224ede1'
    if hashlib.sha256(body.encode()).hexdigest() != expected:
        raise ValueError('The pinned PSMTXConcat generator output changed; revalidate specialization')
    (generated / 'opensmash_concat_reference.h').write_text(
        'static void reference_concat(CPUState* ctx) {\n' +
        re.sub(r'goto return_dispatch_80342140;', 'return;', body) + '}\n')
    optimized = re.sub(r'^label_[0-9A-F]+:\n', '', body, flags=re.M)
    optimized = re.sub(r'    ctx->pc = 0x[0-9A-F]+u;\n', '', optimized)
    optimized = re.sub(r'    if \(!ppc_fp_available\(ctx, 0x[0-9A-F]+u\)\) return;\n', '', optimized)
    optimized = optimized.replace('        if (ctx->exception) return;\n', '')
    def load(m):
        n=m[1]
        return f'ctx->fpr[{n}] = f64_value(convert_to_double(mem_read32(ctx, ea)));\n        ctx->ps1[{n}] = f64_value(convert_to_double(mem_read32(ctx, ea + 4)));'
    optimized, loads = re.subn(r'ppc_psq_load\(ctx, (\d+)u, ea, false, 0u, false, 0x[0-9A-F]+u\);', load, optimized)
    def store(m):
        n=m[1]
        return f'mem_write64(ctx, ea, ((u64)convert_to_single_ftz(f64_bits(ctx->fpr[{n}])) << 32) | convert_to_single_ftz(f64_bits(ctx->ps1[{n}])));'
    optimized, stores = re.subn(r'ppc_psq_store\(ctx, (\d+)u, ea, false, 0u, false, 0x[0-9A-F]+u\);', store, optimized)
    assert (loads, stores) == (13, 6), (loads, stores)
    registers = sorted(set(re.findall(r'ctx->(gpr|fpr|ps1)\[(\d+)\]', optimized)))
    before = '\n'.join(f'    {"u32" if kind == "gpr" else "f64"} {kind}{n} = ctx->{kind}[{n}];' for kind,n in registers)
    after = '\n'.join(f'    ctx->{kind}[{n}] = {kind}{n};' for kind,n in registers)
    optimized = re.sub(r'ctx->(gpr|fpr|ps1)\[(\d+)\]', lambda m:m[1]+m[2], optimized)
    optimized = optimized.replace('goto return_dispatch_80342140;', 'goto finished;')
    guard = """
static bool opensmash_concat(CPUState* ctx) {
    if (!(ctx->msr & PPC_MSR_FP) || !(ctx->hid2 & PPC_HID2_LSQE) ||
        ctx->exception || (ctx->gqr[0] & 0x00070007u) || g_mem_write_journal)
        return false;
    const u32 addresses[] = {ctx->gpr[3], ctx->gpr[4], ctx->gpr[5],
                             ctx->gpr[1] - 64, 0x804d5c00u};
    const u32 sizes[] = {48, 48, 48, 64, 8};
    for (unsigned i = 0; i < 5; i++)
        if (!get_ram_ptr(ctx, addresses[i], sizes[i], NULL)) return false;
    // Exceptional/overflowing values retain the generic path and NaN payload behavior.
    for (unsigned matrix = 0; matrix < 2; matrix++)
        for (unsigned i = 0; i < 12; i++) {
            f32 value = dolrecomp_f32_from_bits(mem_read32(ctx, addresses[matrix] + i * 4));
            if (!(fabsf(value) <= 1.0e10f)) return false;
        }
    if (mem_read32(ctx, 0x804d5c00u) != 0 ||
        mem_read32(ctx, 0x804d5c04u) != 0x3f800000u) return false;
"""
    (generated / 'opensmash_concat.h').write_text(
        '// Generated by tools/specialize_browser_math.py; same arithmetic and register effects.\n' +
        guard + before + '\n' + optimized + '\nfinished:\n' + after + '\n    return true;\n}\n')
    updated = source.replace('#include "../generated.h"', '#include "../generated.h"\n#include "../opensmash_concat.h"')
    updated = updated.replace('label_80342204:\n', 'label_80342204:\n    if (opensmash_concat(ctx)) return;\n')
    if chunk.read_text() != updated: chunk.write_text(updated)




def specialize_scaled(generated=GENERATED):
    chunk=containing_chunk(generated,0x8037A54C)
    boundary=chunk.stem.rsplit('_',1)[1]
    source=chunk.read_text().replace('#include "../opensmash_scaled.h"\n','').replace('    if (opensmash_scaled(ctx)) return;\n','')
    body=source.split('label_8037A54C:\n',1)[1].split('label_8037A610:',1)[0].replace('return_dispatch_'+boundary,'return_dispatch_8037A540')
    if hashlib.sha256(body.encode()).hexdigest() != '2834f44d7f53b2254981298a8595dec1f34fa8f21705148bee4237912de85b7d':
        raise ValueError('The pinned HSD_MtxScaledAdd output changed; revalidate specialization')
    (generated/'opensmash_scaled_reference.h').write_text('static void reference_scaled(CPUState* ctx) {\n'+body.replace('goto return_dispatch_8037A540;','return;')+'}\n')
    optimized=re.sub(r'^label_[0-9A-F]+:\n','',body,flags=re.M)
    optimized=re.sub(r'    ctx->pc = 0x[0-9A-F]+u;\n','',optimized)
    optimized=re.sub(r'    if \(!ppc_fp_available\(ctx, 0x[0-9A-F]+u\)\) return;\n','',optimized)
    registers=sorted(set(re.findall(r'ctx->(gpr|fpr|ps1)\[(\d+)\]',optimized)) | {('fpr','1')})
    before='    CPUState arithmetic;\n    arithmetic.fpscr = ctx->fpscr;\n'
    after='    ctx->fpscr = arithmetic.fpscr;\n'
    for kind,n in registers:
        local=kind+n if kind=='gpr' else f'arithmetic.{kind}[{n}]'
        before+=f'    {"u32 " if kind=="gpr" else ""}{local} = ctx->{kind}[{n}];\n'
        after+=f'    ctx->{kind}[{n}] = {local};\n'
    optimized=re.sub(r'ctx->(gpr|fpr|ps1)\[(\d+)\]',lambda m:m[1]+m[2] if m[1]=='gpr' else f'arithmetic.{m[1]}[{m[2]}]',optimized)
    optimized=optimized.replace('ppc_fmadd_op(ctx,','ppc_fmadd_op(&arithmetic,').replace('goto return_dispatch_8037A540;','goto finished;')
    guard='''static bool opensmash_scaled(CPUState* ctx) {
    if (!(ctx->msr & PPC_MSR_FP) || ctx->exception || g_mem_write_journal)
        return false;
    for(unsigned i=3;i<=5;i++)
        if(!get_ram_ptr(ctx,ctx->gpr[i],48,NULL)) return false;
'''
    (generated/'opensmash_scaled.h').write_text('// Generated from the verified straight-line HSD routine.\n'+guard+before+optimized+'\nfinished:\n'+after+'    return true;\n}\n')
    updated=source.replace('#include "../generated.h"','#include "../generated.h"\n#include "../opensmash_scaled.h"').replace('label_8037A54C:\n','label_8037A54C:\n    if (opensmash_scaled(ctx)) return;\n')
    if chunk.read_text()!=updated:chunk.write_text(updated)

if __name__ == '__main__':
    specialize()
    specialize_scaled()
