# Included after ModernGekko's targets; no launcher UI code is compiled here.
add_executable(opensmash-embedded-test "${OPENSMASH_DESKTOP_SOURCE}/../tests/embedded_memory.cpp")
target_include_directories(opensmash-embedded-test PRIVATE "${OPENSMASH_NATIVE_SOURCE}/native")
target_compile_features(opensmash-embedded-test PRIVATE cxx_std_20)
add_executable(opensmash-character-select-test "${OPENSMASH_DESKTOP_SOURCE}/../tests/character_select_runtime.c")
target_include_directories(opensmash-character-select-test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/include")
if(NOT WIN32)
 target_link_libraries(opensmash-character-select-test PRIVATE m)
endif()
add_executable(opensmash-controllers "${OPENSMASH_DESKTOP_SOURCE}/controllers.cpp")
if(TARGET SDL3-static)
 target_link_libraries(opensmash-controllers PRIVATE SDL3-static)
else()
 target_link_libraries(opensmash-controllers PRIVATE SDL3::SDL3)
endif()
add_library(opensmash-launch MODULE "${OPENSMASH_NATIVE_SOURCE}/mods/launch_match.c")
target_include_directories(opensmash-launch PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/include")
set_target_properties(opensmash-launch PROPERTIES PREFIX "" OUTPUT_NAME "opensmash_launch.mgm")
if(NOT WIN32)
 target_link_libraries(opensmash-launch PRIVATE m)
endif()

if(APPLE)
 set_target_properties(opensmash-launch PROPERTIES SUFFIX ".dylib")
endif()

if(MSVC)
 foreach(target moderngekko-run moderngekko_netplay_session)
  if(TARGET ${target})
   target_compile_definitions(${target} PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
   target_compile_options(${target} PRIVATE /EHsc)
  endif()
 endforeach()
endif()

if(WIN32)
 target_link_libraries(moderngekko PUBLIC videod3d videod3d12)
endif()
